name: TK-TODO Check Action
description: |
  Checks for TK-TODO markers in your codebase that must be resolved before merge.
  Markers can be suppressed by adding 'IGNORE:TK' (case-insensitive) on the same line.
branding:
  icon: check-circle
  color: green

inputs:
  fail-on-found:
    description: "Whether to fail the action if TK-TODO markers are found (default: true)"
    required: false
    default: "true"

outputs:
  found-count:
    description: "Number of TK-TODO markers found"
    value: ${{ steps.check.outputs.found-count }}
  found-markers:
    description: "List of found TK-TODO markers (file:line format)"
    value: ${{ steps.check.outputs.found-markers }}

runs:
  using: "composite"
  steps:
    - name: Check for TK-TODO markers  # IGNORE:TK
      id: check
      shell: bash
      run: |
        # Find all TK-TODO markers (case-insensitive) that don't have IGNORE:TK on the same line  # IGNORE:TK
        # Exit with error if any are found and fail-on-found is true

        echo "Checking for TK-TODO markers..."  # IGNORE:TK

        # Use git ls-files to only check tracked files (excludes gitignored files)
        # grep -i for case-insensitive matching
        # grep -v for excluding lines with IGNORE:TK
        # grep -n for line numbers

        FOUND_TODOS=$(git ls-files | xargs grep -i -n "TK-TODO" 2>/dev/null | grep -i -v "IGNORE:TK" || true)  # IGNORE:TK

        if [ -n "$FOUND_TODOS" ]; then
          # Count the number of markers found
          FOUND_COUNT=$(echo "$FOUND_TODOS" | wc -l | tr -d ' ')
          echo "found-count=$FOUND_COUNT" >> $GITHUB_OUTPUT

          # Save markers to output (base64 encoded to handle special characters)
          echo "found-markers<<EOF" >> $GITHUB_OUTPUT
          echo "$FOUND_TODOS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo ""
          echo "::error::Found $FOUND_COUNT TK-TODO marker(s) that must be resolved before merge"  # IGNORE:TK
          echo ""
          echo "$FOUND_TODOS"
          echo ""
          echo "To suppress a TK-TODO, add 'IGNORE:TK' (case-insensitive) on the same line."  # IGNORE:TK
          echo ""

          if [ "${{ inputs.fail-on-found }}" == "true" ]; then
            exit 1
          fi
        else
          echo "found-count=0" >> $GITHUB_OUTPUT
          echo "found-markers=" >> $GITHUB_OUTPUT
          echo "No unresolved TK-TODO markers found."  # IGNORE:TK
        fi
